import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from './contexts/ThemeContext';
import ThemeLayout from './themeLayout'; // クライアントサイド用のテーマレイアウトをインポート

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-gray-100 text-gray-900">
        <ThemeProvider>
          <ThemeLayout>{children}</ThemeLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
